spring:
  application:
    name: order

  datasource:
    url: jdbc:mysql://localhost:3306/order-db
    username: myuser
    password: mypassword
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect